SuperHeros.UI/Controllers/Events2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperHeros.DATA;

namespace SuperHeros.UI.Controllers {
	[Authorize(Roles = "Admin")]
	public class Events2Controller : Controller {
		private HerosEntities db = new HerosEntities();
		[AllowAnonymous]
		// GET: Events2
		public ActionResult Index() {
			return View(db.Events2.ToList());
		}
		[AllowAnonymous]
		// GET: Events2/Details/5
		public ActionResult Details(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Events2 events2 = db.Events2.Find(id);
			if (events2 == null) {
				return HttpNotFound();
			}
			return View(events2);
		}

		// GET: Events2/Create
		public ActionResult Create() {
			return View();
		}

		// POST: Events2/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "EventID,EventName,Instructor,EventDate,EventTime,EventDescription")] Events2 events2) {
			if (ModelState.IsValid) {
				db.Events2.Add(events2);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(events2);
		}

		// GET: Events2/Edit/5
		public ActionResult Edit(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Events2 events2 = db.Events2.Find(id);
			if (events2 == null) {
				return HttpNotFound();
			}
			return View(events2);
		}

		// POST: Events2/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "EventID,EventName,Instructor,EventDate,EventTime,EventDescription")] Events2 events2) {
			if (ModelState.IsValid) {
				db.Entry(events2).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(events2);
		}

		// GET: Events2/Delete/5
		public ActionResult Delete(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Events2 events2 = db.Events2.Find(id);
			if (events2 == null) {
				return HttpNotFound();
			}
			return View(events2);
		}

		// POST: Events2/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id) {
			Events2 events2 = db.Events2.Find(id);
			db.Events2.Remove(events2);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing) {
			if (disposing) {
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

SuperHeros.UI/Controllers/UserAdminController.cs
using SuperHeros.UI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SuperHeros.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

SuperHeros.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SuperHeros | Material HTML blog template</title>
	<meta name="description"content="Super Hero, Inc., superhero, citizen safety, drop crime rates, villain" />
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
	<!-- Bootstrap -->
	<link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
	<!-- FontAwesome -->
	<link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
	<!-- MaterialCSS -->
	<link rel="stylesheet" href="~/Content/css/material.min.css">
	<!-- RipplesCSS -->
	<link rel="stylesheet" href="~/Content/css/ripples.min.css">
	<!-- ThemeCSS & Responsive CSS -->
	<link rel="stylesheet" href="~/Content/style.css">
	<link rel="stylesheet" href="~/Content/css/responsive.css">
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<header class="header">
		<div data-velocity="-.4" id="particles" class="header-bg"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="social-links">
						<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
						<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
						<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-google-plus"></i> <div class="ripple-wrapper"></div></a>
						<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-youtube"></i> <div class="ripple-wrapper"></div></a>
						<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-linkedin"></i> <div class="ripple-wrapper"></div></a>
					</div>
				</div>
			</div>
		</div>
		<div class="site-title-table">
			<div class="site-title-tablecell">
				<div class="slide-text">
					<h2><a href="index.html"><span>S</span>uper<span>H</span>eros</a></h2>
					<p>Another exciting blog template from awesome team</p>
				</div>
			</div>
		</div>
	</header>
	<section class="maincontent-wrap">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="maincotnent shadow-z-1">
						<div class="mainmenu">
							<div class="navbar navbar-nobg">
								<div class="navbar-header">
									<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</button>
								</div>
								<div class="navbar-collapse collapse">
									<ul class="nav navbar-nav">
										@*<li class="active"><a href="index.html">Home <div class="ripple-wrapper"></div></a></li>*@
										<li>@Html.ActionLink("Home", "Index", "Home")</li>
										<li>@Html.ActionLink("About", "About", "Home")</li>
										<li>@Html.ActionLink("Archive", "Archive", "Home")</li>
										<li>@Html.ActionLink("Single", "Single", "Home")</li>
										<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
										<li>@Html.ActionLink("Events", "Index", "Events2")</li>
										@if (User.IsInRole("Admin") | User.IsInRole("Hero")) {
											<li>@Html.ActionLink("SuperPeoples", "Index", "SuperPeoples")</li>
										}
										@if (User.IsInRole("Admin")) {
											<li>@Html.ActionLink("Alignments", "Index", "Alignments")</li>
											<li>@Html.ActionLink("View Users", "Index", "UsersAdmin")</li>
										}
										<li>@Html.ActionLink("Register", "Register", "Account")</li>
										<li>@Html.ActionLink("Login", "Login", "Account")</li>
									</ul>
								</div>
							</div>
						</div>
						@RenderBody()
					</div>
				</div>
			</div>
		</div>
	</section>
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-6 col-lg-offset-1">
					<div class="footer-wid">
						<h2 class="wid-title">A<span>vengers</span></h2>
						<p>
							Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis
							nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan,
						</p>
					</div>
				</div>
				<div class="col-lg-5 col-md-6">
					<div class="footer-wid">
						<h2 class="wid-title">Newsletter</h2>
						<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
						<div class="newsletter-form">
							<form action="index.html">
								<input class="shadow-z-1" type="email" placeholder="Your Email address">
								<button type="submit" class="btn btn-material-red">Subscribe Now!</button>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="footer-bottom">
						<div class="row">
							<div class="col-md-8">
								<div class="copyright-text">
									<p>© 2015 Avengers - All Rights Reserved. Coded with <i class="fa fa-heart"></i> by <a href="http://wpexpand.com" target="_blank">WP Expand</a></p>
								</div>
							</div>
							<div class="col-md-4">
								<div class="social-links footer-social-links">
									<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
									<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
									<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-google-plus"></i> <div class="ripple-wrapper"></div></a>
									<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-youtube"></i> <div class="ripple-wrapper"></div></a>
									<a class="btn social-link" href="javascript:void(0)"><i class="fa fa-linkedin"></i> <div class="ripple-wrapper"></div></a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="~/Content/js/vendor/jquery-1.11.2.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="~/Content/js/bootstrap.min.js"></script>
	<script src="~/Content/js/material.min.js"></script>
	<script src="~/Content/js/ripples.min.js"></script>
	<script src="~/Content/js/jquery.scrolly.js"></script>
	<script src="~/Content/js/jquery.particleground.min.js"></script>
	<script src="~/Content/js/main.js"></script>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>
@* ----------OLD LAYOUT---------- *@

@*<!DOCTYPE html>
	<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>@ViewBag.Title - My ASP.NET Application</title>
		@Styles.Render("~/Content/css")
		@Scripts.Render("~/bundles/modernizr")

	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					@Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li>@Html.ActionLink("Home", "Index", "Home")</li>
						<li>@Html.ActionLink("About", "About", "Home")</li>
						<li>@Html.ActionLink("Contact", "Contact", "Home")</li>

						@if (Request.IsAuthenticated && User.IsInRole("Admin")) {
							<li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
							<li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
						}
					</ul>
					@Html.Partial("_LoginPartial")
				</div>
			</div>
		</div>
		<div class="container body-content">
			@RenderBody()
			<hr />
			<footer>
				<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
			</footer>
		</div>

		@Scripts.Render("~/bundles/jquery")
		@Scripts.Render("~/bundles/bootstrap")
		@RenderSection("scripts", required: false)
	</body>
	</html>*@